apiVersion: v1
kind: Pod
metadata: 
        name: mypod
        labels:
                app: mypod
spec:
        volumes:
                - name: task-pv-storage
                  persistentVolumeClaim:
                          claimName: task-pv-claim
        containers:
                - name: mypod-container
                  image: ammers/interactive-mnist:v2
                  ports:
                          - containerPort: 80
                            name: "http-server"
                  volumeMounts:
                          - mountPath: "/data"
                            name: task-pv-storage

